# Generated by Django 5.1.2 on 2025-02-05 15:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0002_violation_camera_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunctionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2025, 2, 5, 16, 55, 13, 622402))),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_logs', to='LicenseTracker.car')),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junction_logs', to='LicenseTracker.junktion')),
            ],
        ),
    ]
