# Generated by Django 5.1.2 on 2025-02-05 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0003_junctionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junctionlog',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 17, 0, 3, 435933)),
        ),
    ]
