# Generated by Django 5.1.2 on 2025-02-05 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0004_alter_junctionlog_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junctionlog',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 18, 14, 25, 850609)),
        ),
    ]
