# Generated by Django 5.1.2 on 2025-02-09 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0005_alter_junctionlog_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='junctionlog',
            name='can_be_entered_from',
            field=models.ManyToManyField(blank=True, related_name='can_be_left_towards', to='LicenseTracker.junctionlog'),
        ),
        migrations.AlterField(
            model_name='junctionlog',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 18, 21, 30, 991734)),
        ),
    ]
