# Generated by Django 5.1.2 on 2025-02-09 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0006_junctionlog_can_be_entered_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junctionlog',
            name='can_be_entered_from',
        ),
        migrations.AddField(
            model_name='junktion',
            name='can_be_entered_from',
            field=models.ManyToManyField(blank=True, related_name='can_be_left_towards', to='LicenseTracker.junktion'),
        ),
        migrations.AlterField(
            model_name='junctionlog',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 18, 38, 37, 429657)),
        ),
    ]
