# Generated by Django 5.1.2 on 2025-02-09 18:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0007_remove_junctionlog_can_be_entered_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='junctionlog',
            name='left_towards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_towards', to='LicenseTracker.junktion'),
        ),
        migrations.AlterField(
            model_name='junctionlog',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 19, 12, 57, 300355)),
        ),
    ]
