# Generated by Django 5.1.2 on 2025-02-16 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0008_junctionlog_left_towards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='junctionlog',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 19, 18, 9, 668071)),
        ),
    ]
