from . import views
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('person/', views.view_person_info, name='sample_json_view'),
    path('car/', views.view_cars, name='sample_json_view'),
    path('create_person/', views.create_person, name='person_create'),
    path('update_person/', views.update_person, name='person_update'),
    path('delete_person/', views.delete_person, name='person_delete'),
    path('create_car/', views.create_car, name='person_create'),
    path('update_car/', views.update_car, name='person_update'),
    path('delete_car/', views.delete_car, name='person_delete'),
    path('create_license/', views.create_license, name='person_create'),
    path('update_license/', views.update_license, name='person_update'),
    path('delete_license/', views.delete_license, name='person_delete'),
    path('create_junktion/', views.create_junktion, name='person_create'),
    path('update_junktion/', views.update_junktion, name='person_update'),
    path('delete_junktion/', views.delete_junktion, name='person_delete'),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile_view, name="profile"),
    path("license/", views.license_view, name="license"),
    path("car/add/", views.car_add_view, name="car_add"),
    path("car/list/", views.car_list_view, name="car_list"),
    path("car/<int:car_id>/edit/", views.car_edit_view, name="car_edit"),
    path("car/<int:car_id>/delete/", views.car_delete_view, name="car_delete"),
    # path('carss/', include('LicenseTracker.urls')),
    path('', views.index, name='index'),
    path("persons/", views.all_persons, name="car_list"),
    path("licenses/", views.all_licenses, name="car_list"),
    path("cars/", views.all_cars, name="car_list1"),
    ]
